# Generated by Django 5.1.1 on 2024-10-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='condition',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exercise_habits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise_level',
            field=models.CharField(choices=[('sedentary', 'Ít vận động'), ('lightly_active', 'Vận động nhẹ'), ('moderately_active', 'Vận động vừa phải'), ('very_active', 'Vận động nhiều'), ('super_active', 'Vận động cực nhiều')], default='sedentary', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(),
        ),
    ]
