# Generated by Django 5.1.1 on 2024-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_rename_condition_medicalhistory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exercise_level',
            field=models.CharField(choices=[('sedentary', 'Ít vận động'), ('lightly_active', 'Vận động nhẹ'), ('moderately_active', 'Vận động vừa phải'), ('very_active', 'Vận động nhiều'), ('super_active', 'Vận động cực nhiều')], default='sedentary', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
