# Generated by Django 5.1.1 on 2024-10-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_address_alter_profile_exercise_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
